[cursor]
blink_interval = 500

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 12.0

[font.normal]
family = "Cascursive Nerd Font"
style = "Italic"

[font.bold]
family = "FisaCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCodeICursiveS12 Nerd Font"
style = "Italic"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key9"
mods = "Command"

[scrolling]
history = 10000

[window]
decorations = "full"
# startup_mode = "Windowed"
# opacity = 0.9

[colors.primary]
# background = "#0a0a0a"

[selection]
save_to_clipboard = true

[general]
import = ["~/.dotfiles/alacritty/themes/catppuccin.toml"]
# import = ["~/.dotfiles/alacritty/themes/colors.toml"]
